config/routes.rb
Tapas::Application.routes.draw do

  resources :questions
  resources :lessons
  resources :questiontolessons
  resources :userstats
  resources :topics
  resources :lesson_feedbacks

  root :to => "questions#landing_page" 

  match "/dashboard" => "questions#index"

  match "/about"     => "questions#about"

  devise_for :users
  match "/review/session/:session_id/answers/:question_id" => "questions#review_answer"
  match "/review/all" => "questions#review_all"
  

  match "/admin" => "questions#admin"

  match "/custom_practice" => "questions#custom_practice"
  match "/custom_practice/:error" => "questions#custom_practice"

  match "/decide_start_session" => "questions#decide_start_session"
  match "/nextquestion" => "questions#nextquestion"

  match "/session/:session_id/question/:question_id/subject/:subject/pool/:questionpool" => "questions#session_question"
  match "/session/:session_id/answers/:question_id/order/:order/subject/:subject/pool/:questionpool" => "questions#answer"

  match "/review/:session_id" => "questions#review"
  match "/review/session/:session_id/answers/:question_id" => "questions#review_answer"

  match "/lesson_feedback/lesson/:lesson_id/feedback/:feedback" => "lesson_feedbacks#custom_feedback"

  match "/understand_lesson/lesson/:lesson_id/user/:user_id" => "lesson_feedbacks#understand_lesson"

  match "/resetforadmin" => "questions#adminreset"

end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :correct_response, :difficulty, :image, :incorrect_one, :incorrect_three, :incorrect_two, :other_explanation, :prompt, :supplement, :text_explanation, :title, :topic, :video_explanation, :question_type, :topic_id, :topic_slug
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	before_filter :user_signed_in, :except => [:landing_page, :about, :parsetest]
	before_filter :is_admin, :only => [:new, :create, :edit, :update, :admin]

	def adminreset
		Answer.where(:user_id => current_user.id).delete_all
		@questions = Question.all
		@questions.each do |question|
			answer = Answer.new
			answer.user_id = current_user.id
			answer.question_id = question.id
			answer.result = "Unanswered"
			answer.title = question.title
			answer.difficulty = question.difficulty
			answer.topic = question.topic_slug
			answer.topic_userfacing_name = question.topic
			answer.save
		end

		userstat = Userstat.where(:user_id => current_user.id).first
		if userstat.resetCount == nil
			userstat.resetCount = 1
		else
			userstat.resetCount = userstat.resetCount + 1
		end

		userstat.save

	end


	def landing_page
		if current_user
			redirect_to "/dashboard"
		end
	end

	def about
	end

	def admin
		if !current_user
			redirect_to new_user_session_path
		else
			@questions = Question.all
			@lessons = Lesson.order("lesson_order asc")
			@topics = Topic.order("topic_order asc")
		end
	end

	def custom_practice
		if params[:error]
			@error_message = "yes"
			@message = "There aren't any questions for the filters you selected! Please pick other filters!"
		end

		@topics = Topic.all

	end

	def nextquestion
		@subject = params[:subject]
		@question_pool = params[:questionpool]
		@session = params[:session]

		# Questions answered in this session
		current_session = Answer.where(:practicesession_id => @session)
		current_session_questions = []
		current_session.each do |question|
			current_session_questions << question.question_id
		end

		# If user selects correct/incorrect questions
		if @question_pool == "Correct" || @question_pool == "Incorrect"
			
			potential = Answer.where(:topic => @subject, :result => @question_pool, :user_id => current_user.id)

			potential_questions = []
			potential.each do |question|
				potential_questions << question.question_id
			end
			

			first_question = nil
			potential_questions.each do |potential_question|
				if current_session_questions.include?(potential_question)
				else
					first_question = potential_question
				end
			end


			if first_question == nil
				redirect_to "/review/#{@session}"
				return
			else
				redirect_to "/session/#{@session}/question/#{first_question}/subject/#{@subject}/pool/#{@question_pool}/"
				return
			end
		
		# Unanswered questions
		else
			answered_questions = []
			all_questions_ids = []

			# Get all questions
			all_questions = Question.where(:topic_slug => @subject)
			all_questions.each do |question|
				all_questions_ids << question.id
			end

			puts "all questions: #{all_questions_ids}"
			
			# Get student's answered questions
			answered_questions = Answer.where(:topic => @subject, :user_id => current_user.id)
			answered_questions_ids = []
			answered_questions.each do |answer|
				answered_questions_ids << answer.question_id
			end

			puts "answered questions: #{answered_questions_ids}"

			# Get first unanswered question
			all_questions_ids.each do |potential_question|
				if answered_questions_ids.include? potential_question
				else
					redirect_to "/session/#{@session}/question/#{potential_question}/subject/#{@subject}/pool/#{@question_pool}/"
					return
				end
			end
			redirect_to "/review/#{@session}"
			return

		end
	end

	def decide_start_session
		# if there are enough questions, save session details and redirect to the first question
		
		question_pool = params[:questionpool]
		subject = params[:subject]

		
		# If user selects correct/incorrect questions
		if question_pool == "Correct" || question_pool == "Incorrect"
			
			first_question = Answer.where(:topic => subject, :result => question_pool, :user_id => current_user.id).first
			puts "first question id is #{first_question.question_id}"
			if first_question == nil
				redirect_to "/custom_practice/error"
				return
			else
				practicesession = PracticeSession.new
				practicesession.question_id = first_question.question_id
				practicesession.save
				redirect_to "/session/#{practicesession.id}/question/#{first_question.question_id}/subject/#{subject}/pool/#{question_pool}/"
				return
			end

		# Unanswered questions
		else
			answered_questions = []
			all_questions_ids = []

			# Get all questions
			all_questions = Question.where(:topic_slug => subject)
			all_questions.each do |question|
				all_questions_ids << question.id
			end
			puts all_questions_ids

			
			# Get student's answered questions
			answered_questions = Answer.where(:topic => subject, :user_id => current_user.id)
			answered_questions_ids = []
			answered_questions.each do |answer|
				answered_questions_ids << answer.question_id
			end
			puts answered_questions_ids

			# Get first unanswered question
			all_questions_ids.each do |question|
				if answered_questions_ids.include? question
				else
					session = PracticeSession.new
					session.save
					redirect_to "/session/#{session.id}/question/#{question}/subject/#{subject}/pool/#{question_pool}/"
					return
					break
				end
			end

			@error_message = "You don't have any questions left with these filters!"
			redirect_to "/custom_practice/error"
			return

		end


	end

	def index
		@questions = Question.all
		@lessons = Lesson.paginate(:page => params[:page], :per_page => 10)

		# Get count of questions answered
		@answers = Answer.where(:user_id => current_user.id, :result => ['Correct', 'Incorrect'])
		
		if @answers.count != 0
			puts @answers
			@correct = 0
			@answers.each do |answer|
				if answer.result == "Correct"
					@correct = @correct + 1
				end
			end
			@total = @answers.count
			@percent_correct =  ((@correct.to_f/@total.to_f) * 100).to_int

		else
			# No answers to review because all Unanswered
		end

		understand = UserUnderstandLesson.where(:user_id => current_user.id)
		@lesson_understand = []
		understand.each do |lesson|
			@lesson_understand << lesson.lesson_id
		end

	end

	def new
		@question = Question.new
	end

	def create
	  @question = Question.new(params[:question])
	  if @question.save
	    flash[:notice] = "Question has been created."
	    topic_object = Topic.find(@question.topic_id)
		@question.topic = topic_object.name
		@question.topic_slug = topic_object.topic_slug
		@question.save
	    redirect_to @question
	  else
	    flash[:alert] = "Question has not been created."
	    render :action => "new"
		end
	end

	def show
 		@question = Question.find(params[:id])
	end

	def session_question
 		@question = Question.find(params[:question_id])
 		@subject = params[:subject]
 		@questionpool = params[:questionpool]
 		@session = params[:session_id]
 		
 		@order = rand(1..1000)%5
 		if @order == 0
 			@order = 1
 		end
	end

	def edit
		@question = Question.find(params[:id])
	end

	def update
		@question = Question.find(params[:id])
		if @question.update_attributes(params[:question])
			flash[:notice] = 'Question has been updated.'
			topic_object = Topic.find(@question.topic_id)
			@question.topic = topic_object.name
			@question.topic_slug = topic_object.topic_slug
			@question.save
			redirect_to @question
		else
			flash[:alert] = 'Question has not been updated.'
			render :action => 'edit'
		end
	end

	def destroy
		@question = Question.find(params[:id])
		@question.destroy
		flash[:notice] = 'Question has been deleted.'
		redirect_to "/admin"
	end

	def answer
		@question = Question.find(params[:question_id])
		@order = params[:order].to_i
		@student_response = params[:optionsRadios]
		@question_pool = params[:questionpool]
		@subject = params[:subject]
		@session = params[:session_id]
		
		if @student_response == nil
			@student_response = params[:freeResponseInput]
		end
		
		# Did student get question correct?
		if @question.correct_response == @student_response
			@result = 'Correct'
		else
			@result = 'Incorrect'
		end

		# Update answer record to reflect student's response
		if @question_pool == "Unanswered"
			answer = Answer.new
			answer.result = @result
			answer.title = @question.title
			answer.difficulty = @question.difficulty
			answer.topic_userfacing_name = @question.topic
			answer.studentanswer = @student_response
			answer.user_id = current_user.id
			answer.question_id = @question.id
			answer.topic = @subject
			answer.practicesession_id = @session
			answer.save
		else
			# Student answers an already answered question, just update the response
			answer = Answer.where(:question_id => params[:question_id], :user_id => current_user.id).first
			answer.result = @result
			answer.practicesession_id = @session
			answer.save
		end

		# Get associated lessons for question
		associations = Questiontolesson.where(:question_id => @question.id)
		lessons_array = []
		associations.each do |association|
			lessons_array << association.lesson_id
		end
		@lessons = Lesson.where(:id => lessons_array)

	end


	def review
		@answers = Answer.where(:user_id => current_user.id, :practicesession_id => params[:session_id].to_i)
		@question = 

		@session = PracticeSession.find(params[:session_id])
		
		@correct = 0
		@incorrect = 0
		@answers.each do |answer|
			if answer.result == "Correct"
				@correct = @correct + 1
			else
				@incorrect = @incorrect + 1
			end
		end
		@total = @correct + @incorrect
		@percent_correct =  ((@correct.to_f/@total.to_f) * 100).to_int
	end

	def review_answer
		@question = Question.find(params[:question_id])
		@answer = Answer.where(:user_id => current_user.id, 
								:question_id => params[:question_id], 
								:practicesession_id => params[:session_id]).first
		@session = params[:session_id]
		
		# Did student get question correct?
		if @question.correct_response == @answer.studentanswer
			@result = 'Correct'
		else
			@result = 'Incorrect'
		end

	end

	def review_all
		@answers = Answer.where(:user_id => current_user.id, :result => ['Correct', 'Incorrect'])

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
<p>
    <%= f.label :question_type %> (MC: multipe choice. FR: free response)<br />
    <%= f.text_field :question_type %>
</p>

<p>
    <%= f.label :prompt %><br />
    <%= f.text_area :prompt %>
</p>

<p>
    <%= f.label :supplement %><br />
    <%= f.text_field :supplement %>
</p>

<p>
    <%= f.label :correct_response %><br />
    <%= f.text_field :correct_response %>
</p>

<p>
    <%= f.label :incorrect_one %><br />
    <%= f.text_field :incorrect_one %>
</p>

<p>
    <%= f.label :incorrect_two %><br />
    <%= f.text_field :incorrect_two %>
</p>

<p>
    <%= f.label :incorrect_three %><br />
    <%= f.text_field :incorrect_three %>
</p>

<p>
    <%= f.label :image %><br />
    <%= f.text_field :image %>
</p>



<p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
</p>

<p>
    <%= f.label :topic_id %><br />
    <%= f.text_field :topic_id %>
</p>

<p>
    <%= f.label :topic_slug %> (Leave blank; gets autofilled from above entry)<br />
    <%= f.text_field :topic_slug %>
</p>

<p>
    <%= f.label :topic %> (Leave blank; gets autofilled from above entry)<br />
    <%= f.text_field :topic %>
</p>

<p>
    <%= f.label :difficulty %><br />
    <%= f.text_field :difficulty %>
</p>

<p>
    <%= f.label :video_explanation %><br />
    <%= f.text_field :video_explanation %>
</p>

<p>
    <%= f.label :text_explanation %><br />
    <%= f.text_area :text_explanation %>
</p>

<p>
    <%= f.label :other_explanation %><br />
    <%= f.text_field :other_explanation %>
</p>

<%= f.submit %>

<% end %>

app/views/questions/about.html.erb
about.html.erb

app/views/questions/adminreset.html.erb
Reset!

app/views/questions/answer.html.erb
<div class="alert alert-warning">
	<div class = "row">
        <h5 class = "text-center">
            <% if @question.question_type == "MC" %>
                Choose the best option
            <% else %>
                Enter your answer in the box
            <% end %>
        </h5>
    </div>
</div>

<div class="row">
            
            <div class="col-md-6">
                <p>
                    <%= @question.prompt %>
                </p>

                <p class = "text-center">

                	<% if @question.supplement == "" %>
                	<% else %>
                		<img src = "<%= @question.supplement %>" class="img-rounded" alt="140x140" style="width: 140px; height: 140px;">
                	<% end %>

                	<% if @question.image == "" %>
                	<% else %>
                		<img src = "<%= @question.image %>" class="img-rounded" alt="140x140" style="width: 140px; height: 140px;">
                	<% end %>
                    
                </p>

            </div>
            <!-- end of span6 -->


            <div class="col-md-5 col-md-offset-1">

                <!-- Is it a multiple choice (MC) or free response (FR) question? -->
                <% if @question.question_type == "MC" %>

                    <% if @order == 1 %> 
                        <p >
                            <%= radio_button_tag(:optionsRadios, "#{@question.correct_response}") %>
                            <span class="glyphicon glyphicon-ok" style = "color: #5cb85c;"></span>
                            <%= label_tag(:multiplechoice_correct, "#{@question.correct_response}") %>
                        </p>
                    <% end %>
                    <p>
                    
                    <%= radio_button_tag(:optionsRadios, "#{@question.incorrect_one}") %>
                    <% if @student_response == @question.incorrect_one %>
                        <span class="glyphicon glyphicon-remove" style = "color: #d9534f;"></span>
                    <% end %>
                    <%= label_tag(:multiplechoice_incorrect1, "#{@question.incorrect_one}") %>
                    
                    <% if @order == 2 %> 
                        <p >
                            <%= radio_button_tag(:optionsRadios, "#{@question.correct_response}") %>
                            <span class="glyphicon glyphicon-ok" style = "color: #5cb85c;"></span>
                            <%= label_tag(:multiplechoice_correct, "#{@question.correct_response}") %>
                        </p>
                    <% end %>
                    <p>

                    <%= radio_button_tag(:optionsRadios, "#{@question.incorrect_two}") %>
                    <% if @student_response == @question.incorrect_two %>
                        <span class="glyphicon glyphicon-remove" style = "color: #d9534f;"></span>
                    <% end %>
                    <%= label_tag(:multiplechoice_incorrect2, "#{@question.incorrect_two}") %>
                    
                    <% if @order == 3 %> 
                        <p >
                            <%= radio_button_tag(:optionsRadios, "#{@question.correct_response}") %>
                            <span class="glyphicon glyphicon-ok" style = "color: #5cb85c;"></span>
                            <%= label_tag(:multiplechoice_correct, "#{@question.correct_response}") %>
                        </p>
                    <% end %>

                    <p>
                    
                    <%= radio_button_tag(:optionsRadios, "#{@question.incorrect_three}") %>
                    <% if @student_response == @question.incorrect_three %>
                        <span class="glyphicon glyphicon-remove" style = "color: #d9534f;"></span>
                    <% end %>
                    <%= label_tag(:multiplechoice_incorrect3, "#{@question.incorrect_three}") %>
                    
                    <% if @order == 4 %>
                        <p >
                            <%= radio_button_tag(:optionsRadios, "#{@question.correct_response}") %>
                            <span class="glyphicon glyphicon-ok" style = "color: #5cb85c;"></span>
                            <%= label_tag(:multiplechoice_correct, "#{@question.correct_response}") %>
                        </p>
                    <% end %>

                <% else %>
                <!-- Not a multiple choice question -->

                    <% if @result == "Correct" %>

                        <!-- Disabled input: http://getbootstrap.com/css/ -->
                        <p>
                            <input class = "col-md-5" type="text" disabled="disabled" class="form-control" value="<%= @student_response %>" style="background-color:#C2F0C2;">
                        </p>

                        <br>
                        <p>
                            <span class="glyphicon glyphicon-ok" style = "color: #5cb85c;"></span> Correct!
                        </p>

    
                    <% else %>
                        <p>
                            <input class = "col-md-5" type="text" disabled="disabled" class="form-control" value="<%= @student_response %>" style="background-color:#FFCCCC;">
                        </p>

                        <br>
                        <p>
                            <span class="glyphicon glyphicon-remove" style = "color: #d9534f;"></span> Correct answer: <%= @question.correct_response %>
                        </p>
                    <% end %>

                <% end %>

                <p>

            </div>
            <!-- end of span5 answer choices -->

</div>
<!-- end of row -->

        <div class = "row text-right" style = "margin-top:30px";>
            <div class="col-md-12">
                
                <% if @is_there_next_question == "No" %>
                    <a href = "/review/<%= @session %>" type="button" class="btn btn-success">
                        End session and see results
                    </a>                
                <% else %>
                    
                    <!-- button: next question -->
                    <form action="/nextquestion" method="get">
                        <input type = "hidden" name = "questionpool" value ="<%= @question_pool %>">
                        <input type = "hidden" name = "subject" value ="<%= @subject %>">
                        <input type = "hidden" name = "session" value ="<%= @session %>">
                        <%= submit_tag("Next question", class: "btn btn-success") %>
                    </form>


                    <p><p>
                    
                    <!-- button: end sessions and see results -->
                    <a href = "/review/<%= @session %>" type="button" class="btn btn-success">
                        End session and see results
                    </a>
                <% end %>
            </div>
        </div>

<div class="alert alert-info" style = "margin-top:30px";>
    <div class = "row">
        
        <div class="col-md-4 text-center">                    
            <strong>
                Title
            </strong>
            
            <p>
                <%= @question.title %>
            </p>
        </div>

        <div class="col-md-4 text-center">                    
            <strong>
                Your result
            </strong>
            
            <p>
                <% if @result == "Correct" %>
                    <p style = "color: #5cb85c;"> 
                        <strong><%= @result %></strong>
                    </p>
                <% else %>
                    <p style = "color: #d9534f;"> 
                        <span class="glyphicon glyphicon-remove"></span>
                        &nbsp; <strong><%= @result %></strong>
                    </p>
                <% end %>
                

            </p>
        </div>

        <div class="col-md-4 text-center">                    
            <strong>
                Difficulty
            </strong>
            
            <p>
                <%= @question.difficulty %>
            </p>
        </div>

    </div>
</div>
<!-- end of question desc well -->

<div class = "row" >
    <div class="col-md-6">
        <h4>Video Explanation</h4>
        <iframe width="560" height="315" src="http://www.youtube.com/embed/<%= @question.video_explanation %>" frameborder="0" allowfullscreen></iframe>
    </div>

    <div class="col-md-6">
        <h4>Related Lesson(s)</h4>

                <% @lessons.each do |lesson| %>
                    <p>
                   <div class="media">
                  <a class="pull-left thumbnail" href="/lessons/<%= lesson.id %>">
                    <img src="<%= lesson.thumbnail %>" style="width: 80px; height: 60px;">
                  </a>
                  <div class="media-body">
                    <h5 class="media-heading">
                        <a href = "/lessons/<%= lesson.id %>">
                            <%= lesson.title %>
                        </a>
                             &nbsp; <span class="glyphicon glyphicon-ok"></h5>
                        <p><h6><%= lesson.length %></h6></p>
                  </div>
                </div>
                </p>
                <% end %>

    </div>
</div>
<!-- end of row -->


        <div class = "row">
            <div class="col-md-12">
                <h4>Text Explanation</h4>
                    <%= @question.text_explanation %>
            </div>
        </div>

         <div class = "row text-right" style = "margin-top:30px";>
            <div class="col-md-12">
                <% if @is_there_next_question == "No" %>
                <a href = "/<%= @session %>" type="button" class="btn btn-success">
                    End session and see results
                </a>                
                <% else %>
                <!-- button: next question -->
                    <form action="/nextquestion" method="get">
                        <input type = "hidden" name = "questionpool" value ="<%= @question_pool %>">
                        <input type = "hidden" name = "subject" value ="<%= @subject %>">
                        <input type = "hidden" name = "session" value ="<%= @session %>">
                        <%= submit_tag("Next question", class: "btn btn-success") %>
                    </form>
                <% end %>
            </div>
        </div>

        <div class = "row">
             &nbsp;
        </div>

app/views/questions/custom_practice.html.erb
<% content_for :title do %> - Practice <% end %>
<% content_for :practice_active do %> class = "active" <% end %>

<div class = "row">
    <div class="col-md-12">
        
        <!-- Error message -->
        <% if @error_message == "yes" %>
            <div class="well">
                <center>
                    <%= @message %>
                </center>
            </div>
        <% end %>

        <!-- Header -->
        <h3>
            Start a practice session
        </h3>

    </div>
</div>

<p>

<form action="/decide_start_session" method="get">

<!-- List all subjects -->

<div class="row">
 
    <div class="col-md-2">
        <h4>
            Subjects
        </h4>
    </div>

    <div class="col-md-2">
	    
        
            <p>

                <select name = "subject">
                    <% @topics.each do |topic| %>
                        <option value = "<%= topic.topic_slug %>"> <%= topic.name %></option>
                    <% end %>
                </select>
            </p>
        

	</div>


</div>

<!-- End of listing all subjects -->

<p>

<div class="row">
 
    <div class="col-md-2">
        <h4>
            Question pool
        </h4>
    </div>

    <!-- First column -->
    <div class="col-md-2">
	    <p>

            <select name = "questionpool">
                <option value = "Unanswered">Unanswered</option>
                <option value = "Incorrect">Incorrect</option>
                <option value = "Correct">Correct</option>

             </select>


		</p>
	</div>


</div>


<p>

<div class="row">



</div>

<div class = "row">
	<div class = "col-md-2 col-md-offset-2">
		<%= submit_tag("Start session", class: "btn btn-success") %>
	</div>

</div>
<br>
<div class = "row">
    <div class = "col-md-2 col-md-offset-2">
        <a href = "/resetforadmin" class = "btn btn-info">Reset your question progress</a>
    </div>
</div>

</form>

<!-- end of row -->

app/views/questions/edit.html.erb
<h2>Edit Question</h2>
<%= render 'form' %>

app/views/questions/index.html.erb
<% content_for :title do %> - Dashboard <% end %>
<% content_for :dashboard_active do %> class = "active" <% end %>

<div class = "row">
    <div class="col-md-12">
        <h3>
            Dashboard
        </h3>
    </div>
</div>


<div class="row">
            
    <div class="col-md-4">
        <h4>
            First 10 Lessons <small> <%= link_to "Go to all lessons", lessons_path %></small><hr>
        </h4>

        <% @lessons.each do |lesson| %>
            <p>
                <a href = "/lessons/<%= lesson.id %>"><%= lesson.title %></a>
                &nbsp;<small><%= lesson.length %></small>
               
               <!-- Did student understand lesson? -->
               <% if @lesson_understand.include? lesson.id %>
                    <span class="glyphicon glyphicon-ok">
                <% end %>
            </p>

        <% end %>

        <%= link_to "Go to all lessons", lessons_path , :class => "btn btn-success" %>
        

    </div>
    <!-- end of span4 suggested lessons-->


    <div class="col-md-8">
        <h4>
            Practice <hr>
        </h4>

        <p class = "text-center">
            <a href = "/custom_practice" type="button" class="btn btn-success">Customize Practice Session</a>

            <br>

        </p>

        <h4>
            Results<hr>
        </h4>
        <p>
            

            <% if @answers.count != 0 %>
                You answered <%= @correct %>/<%= @total %> questions correct (<%= @percent_correct %>%). <a href = "/review/all">See detailed results.</a>
            <% else %>
                You haven't answered any questions yet!
            <% end %>

            <br><br>
        </p>

        <!-- Notes module -->
        <!-- <h4>
            Notes<hr>
        </h4>
        You have 4 notes. <a href = "#">View them.</a> -->


        


    </div>
    <!-- end of span8 quick practice -->

</div>
<!-- end of row -->

app/views/questions/landing_page.html.erb
<% content_for :title do %> - Corporate Finance Practice Questions and Video Lessons <% end %>


<div class = "row">
	<div class = "col-md-8 col-md-offset-2">

		<p class = "lead text-center" style = "font-size: 56px;">
			Understand the basics of <strong>Corporate Finance</strong>
			<br><br>
			<a class="btn btn-xlarge btn-success" href="/users/sign_up" style = "padding: 18px 28px; font-size: 30px; line height: normal; -webkit-border-radius: 8px; -moz-border-radius: 8px; border-radius: 8px;">Signup for free</a>
		</p>
		<br>
		<p class = "lead text-center" style = "font-size: 20px; color:#777; font-weight:150;">
			Watch 40+ video lessons and answer 50+ practice questions to test your understanding of important introductory topics in corporate finance
		</p>
		
		<hr>

	</div>

</div>
<!-- end of row div -->


<!-- Screenshot module -->
<div class = "row">
	<div class = "col-md-4 col-md-offset-2">
		<p class = "lead text-center">
			<img src= "https://www.hogblog.org/wp-content/uploads/2014/07/300x300.gif" alt="..." class = "thumbnail ">
		</p>

		<p class = "lead" style = "font-size: 16px;">
			Customizable practice sessions with video explanations for each question
		</p>
	</div>

	<div class = "col-md-4">
		<p class = "lead text-center">
			<img src= "https://www.hogblog.org/wp-content/uploads/2014/07/300x300.gif" alt="..." class = "thumbnail ">
		</p>

		<p class = "lead" style = "font-size: 16px;">
			Video lessons to cover the important introductory topics in corporate finance
		</p>
	</div>

<div class = "col-md-8 col-md-offset-2">
<hr>
</div>


</div>


<!-- STUDENT QUOTE MODULE -->
<div class = "row">
	<div class = "col-md-8 col-md-offset-2">
		
		<p class = "lead" style = "font-size: 20px;">
			<strong>What Students Say</strong>
		</p>
		
		<!-- First quote -->
		<p class = "lead" style = "font-size: 16px;">
			<i>	
				"The videos were helpful, but the <strong>practice questions with vidoe explanations were incredibly helpful.</strong> I'm looking forward to the next finance class!"
			</i>
		</p>

		<!-- Second quote -->
		<p class = "lead" style = "font-size: 16px;">
			<i>	
				"The introductory videos gave me a head start for my finance class this semester. They're great to just brush up on important concepts too."
			</i>
		</p>

		<hr>

	</div>
</div>

<!-- FAQ module -->
<div class = "row">
	<div class = "col-md-8 col-md-offset-2">
		<p class = "lead" style = "font-size: 20px;">
			<strong>Frequently Asked Questions</strong>
		</p>
		<p class = "lead" style = "font-size: 16px;">
			<strong>What if I have a question?</strong>
			<br>
			We're happy to help! Send us an email at <a href = "mailto:sharataka@gmail.com">sharataka@gmail.com</a> and we'll answer you question regariding our service, a lesson video, or help you understand the answer to a problem better!
		</p>

		<p class = "lead" style = "font-size: 16px;">
			<strong>Do you have other classes?</strong>
			<br>
			We're working on it right now! We're going to do a few more classes on more advanced corporate finance topics, accounting, and economics. <a href = "#">Let us know what you want by clicking here and voting!</a>
		</p>

		<p class = "lead text-center">
			<a class="btn btn-xlarge btn-success" href="/users/sign_up" style = "padding: 18px 28px; font-size: 30px; line height: normal; -webkit-border-radius: 8px; -moz-border-radius: 8px; border-radius: 8px;">Signup for free</a>
		</p>
	</div>


</div>

app/views/questions/new.html.erb
<h2>New Question</h2>
<%= render 'form' %>

app/views/questions/parsetest.html.erb
parsetest.html.erb