config/routes.rb
Tapas::Application.routes.draw do

  resources :questions
  resources :lessons
  resources :questiontolessons
  resources :userstats
  resources :topics
  resources :lesson_feedbacks

  root :to => "questions#landing_page" 

  match "/dashboard" => "questions#index"

  match "/about"     => "questions#about"

  devise_for :users
  match "/review/session/:session_id/answers/:question_id" => "questions#review_answer"
  match "/review/all" => "questions#review_all"
  

  match "/admin" => "questions#admin"

  match "/custom_practice" => "questions#custom_practice"
  match "/custom_practice/:error" => "questions#custom_practice"

  match "/decide_start_session" => "questions#decide_start_session"
  match "/nextquestion" => "questions#nextquestion"

  match "/session/:session_id/question/:question_id/subject/:subject/pool/:questionpool" => "questions#session_question"
  match "/session/:session_id/answers/:question_id/order/:order/subject/:subject/pool/:questionpool" => "questions#answer"

  match "/review/:session_id" => "questions#review"
  match "/review/session/:session_id/answers/:question_id" => "questions#review_answer"

  match "/lesson_feedback/lesson/:lesson_id/feedback/:feedback" => "lesson_feedbacks#custom_feedback"

  match "/understand_lesson/lesson/:lesson_id/user/:user_id" => "lesson_feedbacks#understand_lesson"

  match "/resetforadmin" => "questions#adminreset"

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  attr_accessible :lesson_id, :name, :order, :topic_order, :topic_slug
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
before_filter :user_signed_in, :except => []

	def index
		@topics = Topic.order("topic_order asc")
	end

	def new
		@topic = Topic.new
	end

	def create
	  @topic = Topic.new(params[:topic])
	  if @topic.save
	    flash[:notice] = "Topic has been created."
	    redirect_to topics_path
	  else
	    flash[:alert] = "Topic has not been created."
	    render :action => "new"
		end
	end

	def show
 		@topic = Topic.find(params[:id])
 		@lessons = Lesson.where(:topic_id => @topic.id)
	end

	def edit
		@topic = Topic.find(params[:id])
	end

	def update
		@topic = Topic.find(params[:id])
		if @topic.update_attributes(params[:topic])
			flash[:notice] = 'Topic has been updated.'
			redirect_to topics_path
		else
			flash[:alert] = 'Topic has not been updated.'
			render :action => 'edit'
		end
	end

	def destroy
		@topic = Topic.find(params[:id])
		@topic.destroy
		flash[:notice] = 'Topic has been deleted.'
		redirect_to topics_path
	end

	private
	def user_signed_in
		if !current_user
			redirect_to new_user_session_path
		end
	end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>


<p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
</p>

<p>
    <%= f.label :topic_slug %><br />
    <%= f.text_field :topic_slug %>
</p>

<p>
    <%= f.label :topic_order %><br />
    <%= f.text_field :topic_order %>
</p>



<%= f.submit %>

<% end %>

app/views/topics/edit.html.erb
<h2>Edit Topic</h2>
<%= render 'form' %>

app/views/topics/index.html.erb
<a href ="/admin"><- Back to Admin </a>

<h3>Topics <small><%= link_to "Add new topic", new_topic_path %></small></h3>

	<table class="table">
	<thead>
		<th>Topic ID</th>
		<th>Topic Order</th>
		<th>Topic Name</th>
		<th>Edit</th>
		<td>Delete</th>
	</thead>

	<tbody>

		<% @topics.each do |topic| %>
			
			<tr>
				<td>
					<%= topic.id %>
				</td>

				<td>
					<%= topic.topic_order %>
				</td>
				
				<td>
					<%= topic.name %>
				</td>

				<td>
					  <%= link_to "Edit topic", edit_topic_path(topic) %>
				</td>

				<td>
					<a data-confirm="Are you sure?" data-method="delete" href="/topics/<%= topic.id%>" rel="nofollow">Delete</a>
				</td>

			</tr>
		<% end %>

	</tbody>

</table>

app/views/topics/new.html.erb
<h2>New Topic</h2>
<%= render 'form' %>

app/views/topics/show.html.erb
<p><%= link_to "<- Go to all topics", topics_path %></p>

<p>Topic Name: <%= @topic.name %></p>

<p>Topic Order: <%= @topic.id %></p>

<p><%= link_to 'Edit topic', edit_topic_path(@topic) %></p>

<table class="table">
	<thead>
		<th>Lesson ID</th>
		<th>Lesson Order</th>
		<th>Lesson Title</th>
		<th>Edit Lesson</th>
		<th>Delete Lesson</th>
	</thead>

	<tbody>
		<% @lessons.each do |lesson| %>
		<tr>
			<td><%= lesson.id %></td>
			<td><%= lesson.lesson_order %></td>
			<td><a href = "/lessons/<%= lesson.id %>"><%= lesson.title %></a></td>
			<td><%= link_to 'Edit', edit_lesson_path(lesson) %></td>
			<td>
				<a data-confirm="Are you sure?" data-method="delete" href="/lessons/<%= lesson.id%>" rel="nofollow">Delete</a>
			</td>
		</tr>
		<% end %>
	</tbody>

</table>

<br>